export const CREATE_ALERT_REQUEST = 'CREATE_ALERT_REQUEST';
export const CREATE_ALERT_SUCCESS = 'CREATE_ALERT_SUCCESS';
export const CREATE_ALERT_FAILURE = 'CREATE_ALERT_FAILURE';

export const GET_ACTIVE_ALERTS_REQUEST = 'GET_ACTIVE_ALERTS_REQUEST';
export const GET_ACTIVE_ALERTS_SUCCESS = 'GET_ACTIVE_ALERTS_SUCCESS';
export const GET_ACTIVE_ALERTS_FAILURE = 'GET_ACTIVE_ALERTS_FAILURE';

export const GET_TRIGGERED_ALERTS_REQUEST = 'GET_TRIGGERED_ALERTS_REQUEST';
export const GET_TRIGGERED_ALERTS_SUCCESS = 'GET_TRIGGERED_ALERTS_SUCCESS';
export const GET_TRIGGERED_ALERTS_FAILURE = 'GET_TRIGGERED_ALERTS_FAILURE';

export const DELETE_ALERT_REQUEST = 'DELETE_ALERT_REQUEST';
export const DELETE_ALERT_SUCCESS = 'DELETE_ALERT_SUCCESS';
export const DELETE_ALERT_FAILURE = 'DELETE_ALERT_FAILURE';
