export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const APPROVE_USER_REQUEST = 'APPROVE_USER_REQUEST';
export const APPROVE_USER_SUCCESS = 'APPROVE_USER_SUCCESS';
export const APPROVE_USER_FAILURE = 'APPROVE_USER_FAILURE';

export const REJECT_USER_REQUEST = 'REJECT_USER_REQUEST';
export const REJECT_USER_SUCCESS = 'REJECT_USER_SUCCESS';
export const REJECT_USER_FAILURE = 'REJECT_USER_FAILURE';
